services:
  - type: web
    name: dbrain-db-rag
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CHROMA_PERSIST_DIR
        value: ./chroma_db_local
      - key: USE_OLLAMA
        value: "false"
      - key: JINA_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: LANGFUSE_SECRET_KEY
        sync: false
      - key: LANGFUSE_PUBLIC_KEY
        sync: false
      - key: LANGFUSE_HOST
        value: https://cloud.langfuse.com
